spring:
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false
  messages:
    basename: messages
  h2:
    console:
      enabled: true

logging:
  level:
    ROOT: INFO
    br.com.cadsys: DEBUG


server:
  port: 8081

application: