CREATE TABLE TB_USER_PERMISSAO (
	ID_USER VARCHAR(100) NOT NULL,
	ID_PERMISSAO INTEGER NOT NULL,
	PRIMARY KEY (ID_USER, ID_PERMISSAO),
	FOREIGN KEY (ID_USER) REFERENCES TB_USER(ID),
	FOREIGN KEY (ID_PERMISSAO) REFERENCES TB_PERMISSAO(ID)
);